[MISC] Add namespace.
seqan/hibf_lib pull request #13
Opened 2021-07-06 16:54 UTC by MitraDarja

I just added the namespace everywhere, I am not sure, if that is actually what we want... Or if there are things that should even be left out of the namespace...

2021-07-07 10:14 UTC, SGSSGene reviewed
I believe you didn't wanted to but the main function into the hibf namespace :-)

2021-07-07 13:40 UTC, MitraDarja commented
> I believe you didn't wanted to but the main function into the hibf namespace :-)

Ups. :sweat_smile: Thanks for being so observing! :)

2021-08-02 10:42 UTC, eseiler requested changes
Can you add a new line before each closing namespace? Otherwise LGTM

2021-08-02 10:42 UTC, eseiler commented on include/hibf/build/batch.hpp
> +} // namespace hibf
```suggestion
}

} // namespace hibf
```

2021-08-03 10:41 UTC, eseiler approved these changes

2021-08-03 10:41 UTC, merged